// Creat hacking simulator with green background and  shows these messages with random delay of 1 to 7 seconds

// Initializing Hacking...
// Reading Files...
// Password File Detected...
// Sending all password and personal files to server...
// Cleaning up...

// 3 dots must blink